### ISSUE TITLE
hi, syncing, suggestions

### ISSUE THREAD

**Issue by cauerego** [MypaceEngine/PhotoDL4NarrativeServ#1]
hey there Mr mypace/Earth-spinner dude,
thanks so much for building and sharing this!

i noticed you haven't touched the project for almost an year now. granted, narrative guys also haven't done much since then...

anyway, after using your nice piece of software for a while, i noticed it takes way more time than necessary to sync updates. i believe most of this is narrative fault as they probably do not use rsync or anything like it. but i wonder if there would still be a simple and elegant fix for this.

the main issue, actually, is that some new photos are not being downloaded for almost a week now. perhaps it's due a sum of factors which includes this lack of proper handling sync.

also, the notification hardly ever appears, so i never know if it's running unless i open the app. log folder is always empty and TMP folder way too full. two little bugs there in themselves.

as a final suggestion, there would be no need to connect with Google and ask for permissions (thus less code) if you simply throw all files in dcim/narrative without any subfolders. Google photos will pick up from there.

sorry for improperly registering so many things in just one "ticket"... i figured this in itself wouldn't be too big of an issue. :)

ps: project name is so big it broke GitHub mobile gui: it's almost impossible to find the new issue button, unless you know where to look for!

**Comment by MypaceEngine** [comment]
Thank you for your request. I stoped to improve this project, because Number of Narrative Clip User is going down. But I feel happy what you need this application. I will check my application. If i find some bugs, i will fix it. Please wait a few days.

**Comment by cauerego** [comment]
awesome! i'm so glad you're still willing to help. :)

let me just re enforce the 2 main points I'd love to see done:

1st. allowing to set download folder for going to DCIM. (the sub folder structure actually didn't matter as gphotos will work fine, unlike my first experiment had shown, in which it would keep asking to add each single folder inside. i guess that only happens to folders outside dcim.)

2nd. better sync algorithm, which would be like rsync: only copy new files and stop using so much bandwidth when there is just 1 new photo for downloading, for instance.

thank you again for all this!

**Comment by cauerego** [comment]
ping for updated last comment

**Comment by MypaceEngine** [comment]
I fixed some bug, and improved uploading process.
Please use new version.
