### ISSUE TITLE
160px

### ISSUE THREAD

**Issue by cauerego** [MypaceEngine/PhotoDL4NarrativeServ#2]
since the update on March 13 all my photos are being downloaded or uploaded ay tiny 160x160 resolution, no matter which options i select. granted, i tried just a few combinations, mostly to either download to device dcim or not, combined with uploading directly to drive or not.

funny enough, i don't think I've updated the app as soon as the update was released (but maybe i did later in the same day) yet, i just notice my tiny photos date back precisely and coincidentally with March 13th.

cheers again!

**Comment by cauerego** [comment]
ok, not so much the "funny enough" part, after all. in google photos, i do see tiny photos from february as well, duplicated with previous photos which were already uploaded in the correct size... just in my DCIM folder on the android phone that March 13 is the starting date all photos became tiny.

**Comment by MypaceEngine** [comment]
I tested app on my phone today. All of photo size is 2005x2673.
I did not change download algorism form Narrative Service.
I guess Narrative Service do not provide url of full size data. 160x160 is perhaps thumbneil data. This app select biggest size photo from list of photo data. 

Thanks

**Comment by cauerego** [comment]
all my photos in narrative cloud are at full resolution as usual. i uninstalled the app and tried again, still getting only tiny photos.

**Comment by cauerego** [comment]
it is mostly an error on narrative api indeed. i went to https://narrativeapp.com/api/v2/moments/02f7f033fde044d5a9f40cebf3b0432a/photos/ and found this: 

```
{
    "count": 52,
    "next": "https://narrativeapp.com/api/v2/moments/02f7f033fde044d5a9f40cebf3b0432a/photos/?page=2",
    "previous": null,
    "results": [
        {
            "trim": false,
            "uuid": "9c22dbcfe3fc4edaa456056791793d3b",
            "taken_at_local": "2018-04-13T14:22:47+01:00",
            "url": "https://narrativeapp.com/api/v2/photos/9c22dbcfe3fc4edaa456056791793d3b/",
            "tags": [],
            "favorite": false,
            "quality_score": 4.90272131119234,
            "faces_url": "https://narrativeapp.com/api/v2/photos/9c22dbcfe3fc4edaa456056791793d3b/faces/",
            "moment_uuid": "02f7f033fde044d5a9f40cebf3b0432a",
            "favorited_time": null,
            "renders": {
                "g1_thumb_square": {
                    "url": "https://nrtv3-app-privatebucket-1nx6pcmahiqo5.s3.amazonaws.com/private/users/345b22ce9d624f0c9fb73337052a4436/renders/g1_thumb_square/9c22dbcfe3fc4edaa456056791793d3b.jpg",
                    "size": {
                        "width": 133,
                        "height": 100
                    }
                },
                "g1_webrender": {
                    "url": "https://nrtv3-app-privatebucket-1nx6pcmahiqo5.s3.amazonaws.com/private/users/345b22ce9d624f0c9fb73337052a4436/renders/g1_webrender/9c22dbcfe3fc4edaa456056791793d3b.jpg",
                    "size": {
                        "width": 133,
                        "height": 100
                    }
                },
                "g1_hd": {
                    "url": "https://nrtv3-app-privatebucket-1nx6pcmahiqo5.s3.amazonaws.com/private/users/345b22ce9d624f0c9fb73337052a4436/renders/g1_hd/9c22dbcfe3fc4edaa456056791793d3b.jpg",
                    "size": {
                        "width": 133,
                        "height": 100
                    }
                },
                "g1_smartphone": {
                    "url": "https://nrtv3-app-privatebucket-1nx6pcmahiqo5.s3.amazonaws.com/private/users/345b22ce9d624f0c9fb73337052a4436/renders/g1_smartphone/9c22dbcfe3fc4edaa456056791793d3b.jpg",
                    "size": {
                        "width": 133,
                        "height": 100
                    }
                }
            },
            "faces": [],
            "type": "photo"
        },
```

already pinged the guys at narrative... but, at the same time, seems like a very simple change on those lines could help in here too:

https://github.com/MypaceEngine/PhotoDL4NarrativeServ/blob/2bbfa52fc428fe78a5fd03480147402668472b6a/app/src/main/java/com/mypaceengine/downloadnarrative/Job_DownLoadPhoto.java#L77-L78

making it start with `g1_hd` rather than the first item, in case an issue like this happens.

do you think you could kindly make the magic once more? :)

**Comment by MypaceEngine** [comment]
Oh!, I understood the issue. I guess photo size information sending from Narrative Service is not correct. 
I think some one change script or data storing architecture of Narrative Service.
I fix the this bug of my app, and release new version. Please try new version.

**Comment by cauerego** [comment]
https://github.com/MypaceEngine/PhotoDL4NarrativeServ/commit/7944e1b9a863a7e9497bc56f15ad0440fc408aee#diff-d233588577e6e03f3f30b46d60a331b9R68

thank you so much, it worked! :) +1
